### ISSUE TITLE
[fix] 변수 zustand의존 문제

### ISSUE THREAD

**Issue by POL6463** [TU-GitLio/frontend#73]
## 🤔 오류 내용
에러로그 함께 입력  
<br>
페이지 새로고침시 zustand 스토어에만 의존하기에 비어있는값들로 진행되는 오류 해결.
각 페이지 접근시 zustand스토어가 비어있을 경우 다시 한번 fetching하는 로직 추가

## ⚠ 에러 캡쳐 

<br>

**Comment by Jayjunyoung** [comment]
확인했습니다.
